/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package smpractica6;

import java.awt.AlphaComposite;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Composite;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Paint;
import java.awt.Point;
import java.awt.Rectangle;
import java.awt.Stroke;
import java.awt.geom.AffineTransform;
import java.awt.geom.Line2D;

/**
 *
 * @author mariorl
 */
public class LienzoPanel extends javax.swing.JPanel {

    /**
     * Creates new form LienzoPanel
     */
    public LienzoPanel() {
        initComponents();
        this.setSize(1000, 800);
        this.repaint();
    }
    
    @Override
    public void paint(Graphics g){
     super.paint(g);
     Graphics2D g2d = (Graphics2D)g;
     this.pruebaAtributos(g2d);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pruebaAtributos(Graphics2D g2d) {
    //Trazo
    Stroke trazo;
    float patronDiscontinuidad[] = {15.0f, 15.0f, 1.0f, 15.0f};
    trazo = new BasicStroke(10.0f, BasicStroke.CAP_ROUND,BasicStroke.JOIN_MITER, 1.0f, patronDiscontinuidad, 0.0f);
    g2d.setStroke(trazo);
    g2d.draw(new Line2D.Float(40,40,160,160));
    //Relleno
    Paint relleno;
    relleno = new Color(255, 100, 0);
    g2d.draw(new Rectangle(170,40,120,120));
    g2d.fill(new Rectangle(300,40,120,120));
    Point pc1 = new Point(430,40), pc2 = new Point(550,160);
    relleno = new GradientPaint(pc1, Color.RED, pc2, Color.BLUE);
    g2d.setPaint(relleno);
    g2d.fill(new Rectangle(430,40,120,120));
    //Composición
    Composite composicion;
    composicion = AlphaComposite.getInstance(AlphaComposite.SRC_OVER, 0.5f);
    g2d.setComposite(composicion);
    g2d.fill(new Rectangle(190, 100, 200, 120));
    //Transformación
    AffineTransform transformacion;
    // TODO: Código para crear transformación
//    g2d.transform(transformacion);
//    //Fuente
//    Font fuente;
//    // TODO: Código para crear fuente
//    g2d.setFont(fuente);
//    //Renderización
//    RenderingHints render;
//    // TODO: Código para crear renderizado
//    g2d.setRenderingHints(render);
//    //Recorte
//    Shape clip;
//    // TODO: Código para crear clip
//    g2d.setClip(clip);
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
