/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package smmpractica2;

/**
 *
 * @author mariorl
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipa
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        Traza = new javax.swing.ButtonGroup();
        Color = new javax.swing.ButtonGroup();
        BarraHerramientas = new javax.swing.JToolBar();
        ModoLinea = new javax.swing.JToggleButton();
        ModoCuadrado = new javax.swing.JToggleButton();
        ModoElipse = new javax.swing.JToggleButton();
        Lienzo = new javax.swing.JPanel();
        ColoryRelleno = new javax.swing.JPanel();
        Negro = new javax.swing.JToggleButton();
        Rojo = new javax.swing.JToggleButton();
        Azul = new javax.swing.JToggleButton();
        Blanco = new javax.swing.JToggleButton();
        Amarillo = new javax.swing.JToggleButton();
        Verde = new javax.swing.JToggleButton();
        Relleno = new javax.swing.JCheckBox();
        jTextField1 = new javax.swing.JTextField();
        Menu = new javax.swing.JMenuBar();
        Archivo = new javax.swing.JMenu();
        Nuevo = new javax.swing.JMenuItem();
        Abrir = new javax.swing.JMenuItem();
        Guardar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        BarraHerramientas.setBackground(new java.awt.Color(153, 153, 153));
        BarraHerramientas.setRollover(true);
        BarraHerramientas.setName(""); // NOI18N
        BarraHerramientas.setPreferredSize(new java.awt.Dimension(700, 36));

        Traza.add(ModoLinea);
        ModoLinea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/linea.png"))); // NOI18N
        ModoLinea.setFocusable(false);
        ModoLinea.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ModoLinea.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BarraHerramientas.add(ModoLinea);

        Traza.add(ModoCuadrado);
        ModoCuadrado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/rectangulo.png"))); // NOI18N
        ModoCuadrado.setFocusable(false);
        ModoCuadrado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ModoCuadrado.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BarraHerramientas.add(ModoCuadrado);

        Traza.add(ModoElipse);
        ModoElipse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/elipse.png"))); // NOI18N
        ModoElipse.setFocusable(false);
        ModoElipse.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ModoElipse.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BarraHerramientas.add(ModoElipse);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = -574;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(229, 103, 0, 0);
        getContentPane().add(BarraHerramientas, gridBagConstraints);

        Lienzo.setBackground(new java.awt.Color(255, 255, 255));
        Lienzo.setName(""); // NOI18N
        Lienzo.setPreferredSize(new java.awt.Dimension(700, 700));
        Lienzo.setLayout(new javax.swing.BoxLayout(Lienzo, javax.swing.BoxLayout.LINE_AXIS));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.ipadx = 700;
        gridBagConstraints.ipady = 700;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(Lienzo, gridBagConstraints);

        ColoryRelleno.setBackground(new java.awt.Color(153, 153, 153));
        ColoryRelleno.setPreferredSize(new java.awt.Dimension(700, 61));

        Negro.setBackground(new java.awt.Color(0, 0, 0));
        Color.add(Negro);
        Negro.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Negro.setBorderPainted(false);
        Negro.setMaximumSize(new java.awt.Dimension(5, 5));
        Negro.setPreferredSize(new java.awt.Dimension(20, 20));

        Rojo.setBackground(new java.awt.Color(255, 0, 0));
        Color.add(Rojo);
        Rojo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Rojo.setPreferredSize(new java.awt.Dimension(20, 20));

        Azul.setBackground(new java.awt.Color(0, 0, 255));
        Color.add(Azul);
        Azul.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Azul.setPreferredSize(new java.awt.Dimension(20, 20));

        Blanco.setBackground(new java.awt.Color(255, 255, 255));
        Color.add(Blanco);
        Blanco.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Blanco.setPreferredSize(new java.awt.Dimension(20, 20));

        Amarillo.setBackground(new java.awt.Color(255, 255, 0));
        Color.add(Amarillo);
        Amarillo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Amarillo.setPreferredSize(new java.awt.Dimension(20, 20));

        Verde.setBackground(new java.awt.Color(0, 255, 0));
        Color.add(Verde);
        Verde.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Verde.setPreferredSize(new java.awt.Dimension(20, 20));

        Relleno.setBackground(new java.awt.Color(153, 153, 153));
        Relleno.setText("Relleno");
        Relleno.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout ColoryRellenoLayout = new javax.swing.GroupLayout(ColoryRelleno);
        ColoryRelleno.setLayout(ColoryRellenoLayout);
        ColoryRellenoLayout.setHorizontalGroup(
            ColoryRellenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ColoryRellenoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ColoryRellenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ColoryRellenoLayout.createSequentialGroup()
                        .addComponent(Blanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Amarillo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Verde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ColoryRellenoLayout.createSequentialGroup()
                        .addComponent(Negro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Rojo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Azul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Relleno)
                .addContainerGap())
        );
        ColoryRellenoLayout.setVerticalGroup(
            ColoryRellenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ColoryRellenoLayout.createSequentialGroup()
                .addGroup(ColoryRellenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ColoryRellenoLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(Relleno))
                    .addGroup(ColoryRellenoLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(ColoryRellenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Azul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Rojo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Negro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ColoryRellenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Blanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Amarillo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Verde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = -536;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(217, 0, 0, 0);
        getContentPane().add(ColoryRelleno, gridBagConstraints);

        jTextField1.setBackground(new java.awt.Color(153, 153, 153));
        jTextField1.setText("Barra de estado");
        jTextField1.setPreferredSize(new java.awt.Dimension(700, 10));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = -685;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(236, 0, 0, 0);
        getContentPane().add(jTextField1, gridBagConstraints);

        Menu.setBackground(new java.awt.Color(204, 204, 204));

        Archivo.setText("Archivo");

        Nuevo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Nuevo.setText("Nuevo");
        Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoActionPerformed(evt);
            }
        });
        Archivo.add(Nuevo);

        Abrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Abrir.setText("Abrir");
        Archivo.add(Abrir);

        Guardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Guardar.setText("Guardar");
        Archivo.add(Guardar);

        Menu.add(Archivo);

        setJMenuBar(Menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NuevoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Abrir;
    private javax.swing.JToggleButton Amarillo;
    private javax.swing.JMenu Archivo;
    private javax.swing.JToggleButton Azul;
    private javax.swing.JToolBar BarraHerramientas;
    private javax.swing.JToggleButton Blanco;
    private javax.swing.ButtonGroup Color;
    private javax.swing.JPanel ColoryRelleno;
    private javax.swing.JMenuItem Guardar;
    private javax.swing.JPanel Lienzo;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JToggleButton ModoCuadrado;
    private javax.swing.JToggleButton ModoElipse;
    private javax.swing.JToggleButton ModoLinea;
    private javax.swing.JToggleButton Negro;
    private javax.swing.JMenuItem Nuevo;
    private javax.swing.JCheckBox Relleno;
    private javax.swing.JToggleButton Rojo;
    private javax.swing.ButtonGroup Traza;
    private javax.swing.JToggleButton Verde;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
